package com.LeverInc.Project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class App extends Application
{
	public static void main(String[] args) {
		try {
			// Create and load the database
			Connection conn = DriverManager.getConnection(Environment.DB_URL);
			System.out.println("Connection created to DB!");

			// CREATE A TABLE
			// 1. Create a Statement from the database connection
			Statement stmt = conn.createStatement();

//			try {
//				String dropTable = "drop table Favorites";
//				stmt.execute(dropTable);
//				System.out.println("Favorites table dropped.");
//			} catch (SQLException e) {
//				System.out.println("Favorites table does not exist.");
//			}
//
//			// 2. Make a SQL statement to create the table
//			String sqlCreateTable = "CREATE Table Favorites(" 
//							+ " Fav_ID int NOT NULL GENERATED BY DEFAULT AS IDENTITY,"
//							+ " Fav_Name varchar(255),"
//							+ " Fav_URL varchar(255)," 
//							+ " PRIMARY KEY (Fav_ID))";
//
//			// 3. Execute the statement
//			stmt.execute(sqlCreateTable);
//			// TABLE IS CREATED!
//
////			addFavorite(conn, "Google", "google.com");
////			addFavorite(conn, "Amazon", "amazon.com");
////			addFavorite(conn, "Facebook", "facebook.com");
////			addFavorite(conn, "Twitch", "twitch.tv");
////			addFavorite(conn, "CNN", "cnn.com");

			String selectStatement = "SELECT Fav_ID, Fav_Name, Fav_URL FROM Favorites";
			ResultSet result = stmt.executeQuery(selectStatement);

			// Prints out favorites
			System.out.println("\n-----------------FAVORITES-----------------\n");

			while (result.next()) {
				System.out.printf("%-4d %-10s %-10s\n", result.getInt("Fav_ID"), result.getString("Fav_Name"), result.getString("Fav_URL"));
			}

			System.out.println("\n-------------------------------------------\n");

			conn.close();
			System.out.println("Connection closed.");
		} catch (SQLException e) {
			System.out.println("Error: " + e.getMessage());
			e.printStackTrace();
		}
		
		// JavaFX GUI to lookup and update records
		launch(args);
		
	}

	// Method for inserting new favorite url(s) into Favorites Table
	public static void addFavorite(Connection conn, String favName, String favURL) {
		try {
			Statement stmt = conn.createStatement();
			String insertFavorite = String.format(
					"INSERT into Favorites(Fav_Name, Fav_URL)" + " values ('%s', '%s')", favName, favURL);
			stmt.executeUpdate(insertFavorite);
			System.out.println("Favorite added!");
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	public void start(Stage stage) throws Exception {
		Parent parent = FXMLLoader.load(getClass().getResource("EliteBrowser.fxml"));
		Scene scene = new Scene(parent);
		stage.setTitle("Elite Browser");
		stage.setScene(scene);
		stage.show();
	}
	
}