package com.LeverInc.Project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

// REQ #4
public class Database implements Launch {

	public static void main(String[] args) {
		
		try {
			// Create and load the database
			Connection conn = DriverManager.getConnection(Environment.DB_URL);
			System.out.println("Connection created to DB!");

			// CREATE A TABLE
			// 1. Create a Statement from the database connection
			Statement stmt = conn.createStatement();
			
			// REQ #11
			try {
				String dropTable = "drop table Favorites";
				stmt.execute(dropTable);
				System.out.println("Favorites table dropped.");
			} catch (SQLException e) {
				System.out.println("Favorites table does not exist.");
			}

			// 2. Make a SQL statement to create the table
			String sqlCreateTable = "CREATE Table Favorites(" 
							+ " Fav_ID int NOT NULL GENERATED BY DEFAULT AS IDENTITY,"
							+ " Fav_Name varchar(255),"
							+ " Fav_URL varchar(255)," 
							+ " PRIMARY KEY (Fav_ID))";

			// 3. Execute the statement
			stmt.execute(sqlCreateTable);
			// TABLE IS CREATED!
			
			try {
				String dropTable = "drop table Preferences";
				stmt.execute(dropTable);
				System.out.println("Preferences table dropped.");
			} catch (SQLException e) {
				System.out.println("Preferences table does not exist.");
			}

			// 2. Make a SQL statement to create the table
			sqlCreateTable = "CREATE Table Preferences(" 
							+ " Window_Color varchar(50) NOT NULL PRIMARY KEY)";

			// 3. Execute the statement
			stmt.execute(sqlCreateTable);
			// TABLE IS CREATED!
			
			String insertPreference = String.format(
					"INSERT into Preferences(Window_Color)" + " values ('#F9F9F9')");
			stmt.executeUpdate(insertPreference);

//			Environment.addFavorite("Google", "google.com");
//			Environment.addFavorite("Amazon", "amazon.com");
//			Environment.addFavorite("Facebook", "facebook.com");
//			Environment.addFavorite("Twitch", "twitch.tv");
//			Environment.addFavorite("CNN", "cnn.com");

			String selectStatement = "SELECT Fav_ID, Fav_Name, Fav_URL FROM Favorites";
			ResultSet result = stmt.executeQuery(selectStatement);

			// Prints out favorites
			System.out.println("\n-----------------FAVORITES-----------------\n");

			while (result.next()) {
				System.out.printf("%-4d %-10s %-10s\n", result.getInt("Fav_ID"), result.getString("Fav_Name"), result.getString("Fav_URL"));
				//System.out.printf("%d \t %s\n", result.getInt("Fav_ID"), result.getString("Fav_Name"));
				//System.out.printf("\t %s \n\n", result.getString("Fav_URL"));
			}

			System.out.println("\n-------------------------------------------\n");

			conn.close();
			System.out.println("Connection closed.");
		} catch (SQLException e) {
			System.out.println("Error: " + e.getMessage());
			e.printStackTrace();
		}
	}

}
